log_file: test
tasks:
        Stats:
                delay: 10 #seconds
                modules:
                        - average_entry_count
                        - print_most_hit
        Alerts:
                average_over: 120 #seconds
                request_frequency_threshold: 10 #requests per second
                update_time: 1 #seconds
